### ISSUE TITLE
Cannot call export_graph with image_size different from default

### ISSUE THREAD

**Issue by cpury** [vanhuyz/CycleGAN-TensorFlow#21]
If your `image_size` is different from 256, calling `export_graph` won't work. E.g. if `image_size < 256`, errors are thrown that certain weights and biases could not be found in the checkpoint.

**Solution:**
`image_size` needs to be passed to the `CycleGAN` constructor, otherwise the network will have the wrong structure. Adding `image_size=FLAGS.image_size` to the parameters fixed this for me.

**Comment by vanhuyz** [comment]
Nice! Could you send me a pull request?

**Comment by cpury** [comment]
https://github.com/vanhuyz/CycleGAN-TensorFlow/pull/25 👍
