### ISSUE TITLE
ngf=64?

### ISSUE THREAD

**Issue by theflashsean1** [vanhuyz/CycleGAN-TensorFlow#32]
Hi, shouldn't default ngf=32, since you're trying to get 32 feature maps after 1st convolution?

**Comment by vanhuyz** [comment]
At first, I set ngf=32 according to the original paper. But I've changed to 64 after realizing that the authors are using ngf=64 in their code: https://github.com/junyanz/CycleGAN/blob/master/options.lua#L12

**Comment by theflashsean1** [comment]
I see, thanks!
