### ISSUE TITLE
Sorry if it is irrelevant to this project: this TensorFlow binary was not compiled to use: AVX

### ISSUE THREAD

**Issue by 2efPer** [vanhuyz/CycleGAN-TensorFlow#39]
It may be my environment's problem, but I really no idea how to handle it.I even don't understand what is this mean.

> $a@a >python  inference.py --model pretrained/man2woman.pb --input data/test.jpg --output data/output.jpg --image_size 256
> 2017-09-06 16:39:42.586351: I C:\tf_jenkins\home\workspace\nightly-win\M\window
\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports ins
ructions that this TensorFlow binary was not compiled to use: AVX

Is it caused by model or platform??

**Comment by pazzjurist** [comment]
That's your platform. Compile TF from source to not get that message.
