### ISSUE TITLE
How should I stop training?

### ISSUE THREAD

**Issue by Chen65010445** [vanhuyz/CycleGAN-TensorFlow#45]
After 10000 steps to train the mode, the training progress continued. How should I stop it? Or how should I change in the code to change this situation?

**Comment by vanhuyz** [comment]
You can stop the training progress anytime you want by Ctrl+C.
Or if you want to stop after 10000 steps, simply modify [this line](https://github.com/vanhuyz/CycleGAN-TensorFlow/blob/master/train.py#L89)  as follows:

```diff
- while not coord.should_stop():
+ while step < 10000 and not coord.should_stop():
```

**Comment by Chen65010445** [comment]
Thank you, that would be very grateful to me.
