### ISSUE TITLE
tf.gfile.FastGFile does not work on 'b' mode

### ISSUE THREAD

**Issue by Zardinality** [vanhuyz/CycleGAN-TensorFlow#5]
In [here](https://github.com/vanhuyz/CycleGAN-TensorFlow/blob/master/dump.py#L76) `tf.gfile.FastGFile` use 'b' mode. While with Python3.4 and Python3.5 it returns an error like: `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte`.
Using 'rb' mode is okay for me.

**Comment by vanhuyz** [comment]
Thanks, I fixed it 😊
