### ISSUE TITLE
What's the possible reasons about the wrong image inferenced by my own model?

### ISSUE THREAD

**Issue by WhatTheNathan** [vanhuyz/CycleGAN-TensorFlow#52]
I used monet2photo downloaded from https://github.com/junyanz/CycleGAN
the trainning step is 9100,
the other parameters are all default,
and the result looks like this
<img width="733" alt="screen shot 2017-12-05 at 4 02 45 pm" src="https://user-images.githubusercontent.com/22427632/33596526-f28bcd4c-d9d6-11e7-824e-29285eaf1708.png">
What's the possible reasons?

**Comment by vanhuyz** [comment]
By default, checkpoints are autosaved every 10000 steps. One possible reason is you exported the model too soon then the exported model actually just trained by only 1 step instead of 9100 steps.

By the way, 9100 steps are not enough in most cases. You can check Tensorboard to see the progress.

**Comment by WhatTheNathan** [comment]
wow, thank you so much for the answer, I will try it again.
