### ISSUE TITLE
Why do you set the true label as 0.9?

### ISSUE THREAD

**Issue by u10116032** [vanhuyz/CycleGAN-TensorFlow#62]
Hi, first of all, thanks for this great work!!

But I'm curious that why do you set the true label as 0.9?

I don't find any description in CycleGAN paper.

Is there any problem that setting true label as 1.0?

Thanks for your explanation :)

**Comment by vanhuyz** [comment]
Nice catch!
I was mimicking the original implementation (in lua), but it looks like the authors have changed their code: https://github.com/junyanz/CycleGAN/commit/38a292e40627f18bed433bfb03d2aa025faa265c

**Comment by u10116032** [comment]
Wow I'm truly surprised by your quick reply!!

Haha curious about the difference, maybe I can do some experiment later,

Thanks for your reply again :)
