### ISSUE TITLE
tf.variable_scope with tf.AUTO_REUSE

### ISSUE THREAD

**Issue by meeio** [vanhuyz/CycleGAN-TensorFlow#69]
what if i change:
`with tf.variable_scope(self.name, reuse=self.reuse)`
to:
`with tf.variable_scope(self.name, reuse=tf.AUTO_REUSE)`
will it get same result?

**Comment by vanhuyz** [comment]
Yeah, it looks like we can use the new `tf.AUTO_REUSE` API.
