### ISSUE TITLE
The effect of ImagePool

### ISSUE THREAD

**Issue by weizequan** [vanhuyz/CycleGAN-TensorFlow#72]
Hello,
  What is the effect of using imagepool? This can make the training of discriminator more stable?

**Comment by see--** [comment]
Yes, it is this section from the Paper:

> Second, to reduce model oscillation [14], we follow
Shrivastava et al’s strategy [45] and update the discrimina-
tors using a history of generated images rather than the ones
produced by the latest generative networks. We keep an im-
age buffer that stores the 50 previously generated images.
