### ISSUE TITLE
A question about the model pipeline

### ISSUE THREAD

**Issue by FesianXu** [vanhuyz/CycleGAN-TensorFlow#82]
Hi, vanhuyz, this work is really impressive! 
I have a question.In the 78 lines at `model.py` file, there is the code:

`D_Y_loss = self.discriminator_loss(self.D_Y, y, self.fake_y, use_lsgan=self.use_lsgan)`

why we use `self.fake_y` instead of the simple `fake_y`, since the tensor `fake_y` has been generated above by code 'fake_y = self.G(x)'. it seems more like a pipeline without placeholder to feed the `self.fake_y`. Thanks for any explanation:)

**Comment by beshining** [comment]
self.fake_y is a sample image from a pool of fake images, while fake_y is the generater's output given y as input. Generally, using a fake image which is not relevant to the current input real image wiil be of benefit to the training process, making it more stable.

**Comment by FesianXu** [comment]
@beshining
“Generally, using a fake image which is not relevant to the current input real image will be of benefit to the training process, making it more stable.” Does it have any reference?
